apiVersion: v1
kind: Secret
metadata:
  name: "%(name)s.service-account-token"
  namespace: "%(namespace)s"
  annotations:
    kubernetes.io/service-account.name: "%(name)s"
type: kubernetes.io/service-account-token
