apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "%(name)s"
  namespace: "%(namespace)s"
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - list
      - watch
      - create
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtemplates
    verbs:
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resourceNames: []
    resources:
      - workflowtemplates
    verbs:
      - get
